# Generated by Django 5.0.1 on 2024-01-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisories',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alerts',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
