# Generated by Django 5.0.1 on 2024-01-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_advisories_name_alerts_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisories',
            name='date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
