# Generated by Django 5.0.1 on 2024-01-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_advisories_date_alter_alerts_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisories',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='advisories',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='advisories',
            name='subject',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='subject',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
